### PR TITLE
Add phpunit test to check for no id and no params conditions for clone scheduled job functionality

### PR DESCRIPTION
**Pull request by tiotsop01**
Overview
----------------------------------------
The current test, tests that if you call the clone API with an array with the ID of an existing job, it creates a new job. But what if we call the clone API with no parameters or what if we call it with an id for a job that doesn't exist?

Before
----------------------------------------
 The test checks that if you call the clone API with an array with the ID of an existing job, it creates a new job.

After
----------------------------------------
In addition to testing that if you call the clone API with an array with the ID of an existing job, it creates a new job, also checks for no id and no params conditions

Comments
----------------------------------------
This is a PR on another PR

### CODE REVIEW

**Comment by michaelmcandrew** [comment]
@tiotsop01 - looks like something has gone a bit wrong - there are 96 commits and 89 changed files in this PR. 

I would expect it to just include your single commit: https://github.com/mattwire/civicrm-core/pull/1/commits/821ea0265b0ac92ac7d6a2b66be16ed643bc43fe

**Comment by michaelmcandrew** [comment]
@tiotsop01 the commit looks good though. One suggestion. You could add another test that tests with a ID that we are sure does not exist, e.g id=1000000000

**Comment by tiotsop01** [comment]
I don't know why this happens. Still looking up on how to make it show just
my single commits

On Wed, May 16, 2018 at 11:21 AM, Michael McAndrew <notifications@github.com

**Comment by tiotsop01** [comment]
Thanks for the review, let me do that right away!

On Wed, May 16, 2018 at 11:24 AM, Michael McAndrew <notifications@github.com

**Comment by michaelmcandrew** [comment]
@tiotsop01 - looking above, it says "tiotsop01 wants to merge 97 commits into *mattwire:master* from tiotsop01:devcore-clone-jobs-test".

I think you should be doing your PR onto matt wire's *devcore47_clone_scheduled_jobs* branch.

Have you tried creating another PR onto that branch?

**Comment by tiotsop01** [comment]
@michaelmcandrew  Yes I tried creating the PR initially to *devcore47_clone_scheduled_jobs*
but I keep having conflict which I couldn't resolve because the PR in that
branch has not been merged for me to fetch changes

**Comment by michaelmcandrew** [comment]
you should be able to fetch the branch from matt wire's repo with something like
```
git remote add mattwire https://github.com/mattwire/civicrm-core
git fetch mattwire
git checkout devcore47_clone_scheduled_jobs
```

**Comment by mattwire** [comment]
@tiotsop01 It may be easier to just create another PR against civicrm/civicrm-core with just the additional unit tests.  Then it can be tested/merged once the original PR is merged

**Pull request closed without merging**
